In [2]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

In [3]:
iris = load_iris()
x = iris.data
y = iris.target
print(x)

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)
# 데이터를 pytorch 텐서로 변환
x_train = torch.from_numpy(x_train).float()
y_train = torch.from_numpy(y_train).long()
x_test = torch.from_numpy(x_test).float()
y_test = torch.from_numpy(y_test).long()

train_dataset = TensorDataset(x_train, y_train)
train_loader = DataLoader(train_dataset, batch_size=10, shuffle=True)



[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [3]:
class SoftmaxRegression(nn.Module):
    def __init__(self, input_size, num_classes):
        super(SoftmaxRegression, self).__init__()
        self.linear = nn.Linear(input_size, num_classes)
    
    def forward(self,x):
        out = self.linear(x)
        return out

In [4]:
input_size = 4
num_classes = 3
lr = 0.01
num_epoches = 100

In [5]:
model = SoftmaxRegression(input_size, num_classes)
criterion = nn.CrossEntropyLoss()
optimizer = optim.SGD(model.parameters(), lr=lr)

In [6]:
total_step = len(train_loader)
for epoch in range(num_epoches):
    for i, (inputs, labels) in enumerate(train_loader):
        outputs = model(inputs)
        loss = criterion(outputs, labels)
        
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        
        if (i+1) == 12:
            print(f'Epoch: {epoch+1}/ {num_epoches}, Step: {i+1}/{total_step}, Loss: {loss:.2f}')

Epoch: 1/ 100, Step: 12/12, Loss: 0.97
Epoch: 2/ 100, Step: 12/12, Loss: 0.91
Epoch: 3/ 100, Step: 12/12, Loss: 0.86
Epoch: 4/ 100, Step: 12/12, Loss: 0.77
Epoch: 5/ 100, Step: 12/12, Loss: 0.76
Epoch: 6/ 100, Step: 12/12, Loss: 0.65
Epoch: 7/ 100, Step: 12/12, Loss: 0.79
Epoch: 8/ 100, Step: 12/12, Loss: 0.76
Epoch: 9/ 100, Step: 12/12, Loss: 0.85
Epoch: 10/ 100, Step: 12/12, Loss: 0.58
Epoch: 11/ 100, Step: 12/12, Loss: 0.78
Epoch: 12/ 100, Step: 12/12, Loss: 0.64
Epoch: 13/ 100, Step: 12/12, Loss: 0.67
Epoch: 14/ 100, Step: 12/12, Loss: 0.67
Epoch: 15/ 100, Step: 12/12, Loss: 0.65
Epoch: 16/ 100, Step: 12/12, Loss: 0.67
Epoch: 17/ 100, Step: 12/12, Loss: 0.59
Epoch: 18/ 100, Step: 12/12, Loss: 0.67
Epoch: 19/ 100, Step: 12/12, Loss: 0.42
Epoch: 20/ 100, Step: 12/12, Loss: 0.62
Epoch: 21/ 100, Step: 12/12, Loss: 0.57
Epoch: 22/ 100, Step: 12/12, Loss: 0.54
Epoch: 23/ 100, Step: 12/12, Loss: 0.64
Epoch: 24/ 100, Step: 12/12, Loss: 0.61
Epoch: 25/ 100, Step: 12/12, Loss: 0.52
Epoch: 26

In [7]:
model.eval()
with torch.no_grad():
    outputs = model(x_test)
    _, predicted = torch.max(outputs.data, 1)
    accuracy = (predicted == y_test).sum().item() / len(y_test)
    print('Test Accuracy: ', accuracy)

Test Accuracy:  1.0
